"use client";

import {useState, type FormEvent, type ReactNode} from "react";
import {motion,useReducedMotion,useScroll,useSpring,AnimatePresence} from "framer-motion";
import {ArrowDownRight,ArrowUpRight,Check,Copy,Instagram,Mail,Menu,X,PenLine,Video,Users,Landmark,Send,Phone,ChevronDown,ArrowRight} from "lucide-react";

const EMAIL="zanaibfamiya@gmail.com";
const INSTA="https://www.instagram.com/hehe_ussss/";
const WHATSAPP="https://wa.me/923319743275";
const categories=["All work","Writing","Creative","Leadership","Finance"] as const;
type Category=typeof categories[number];
type Project={category:Exclude<Category,"All work">;number:string;eyebrow:string;name:string;role:string;period:string;metric:string;metricLabel:string;details:string[]};
const projects:Project[]=[
 {category:"Writing",number:"01",eyebrow:"FREELANCE / SEO SPECIALIST",name:"Words engineered\nto get found.",role:"Self-employed",period:"2024 — Present",metric:"1,000+",metricLabel:"SEO ARTICLES · 10+ INDUSTRIES",details:["Managed concurrent content pipelines supporting organic search traffic growth.","Applied semantic keyword strategies and tailored tone for technical and niche brands."]},
 {category:"Creative",number:"02",eyebrow:"INSTAGRAM / VIDEO EDITING",name:"Make them stop.\nMake them watch.",role:"Content Creator — @hehe_ussss",period:"2025 — Present",metric:"360°",metricLabel:"END-TO-END VIDEO PRODUCTION",details:["Concepted, shot and edited Instagram Reels and short-form video assets.","Used trending formats, pacing and retention-focused editing to maximize reach and channel growth."]},
 {category:"Leadership",number:"03",eyebrow:"IBF SOCIETY / LEADERSHIP",name:"Lead with purpose.\nDeliver with people.",role:"First Female Vice President — BZU",period:"Bahauddin Zakariya University",metric:"20+",metricLabel:"TEAM MEMBERS · 5+ MAJOR EVENTS",details:["Elected to lead student society operations while maintaining a 3.67 CGPA.","Led strategic communication, public speaking and university event logistics."]},
 {category:"Finance",number:"04",eyebrow:"FINANCE / BANKING INTERNSHIPS",name:"Precision behind\nthe numbers.",role:"United Bank Limited & Lahore Gymkhana",period:"Internships",metric:"4+",metricLabel:"BANKING DEPARTMENTS · AUDIT REVIEW",details:["Conducted internal audit reviews and compliance checks at UBL.","Managed financial record-keeping, ledgers and reconciliation at Lahore Gymkhana."]}
];
const services=[
 {number:"01",name:"SEO Content &\nLong-form Writing",summary:"Crafting search-optimized articles, long-form blogs and website copy tailored to brand voice, search intent and semantic SEO.",tags:["SEO ARTICLES","WEB COPY","CONTENT STRATEGY"],icon:PenLine},
 {number:"02",name:"Video Editing &\nShort-form Content",summary:"End-to-end Instagram Reels production — scripting, shooting and editing with an eye for retention and authentic connection.",tags:["REELS","VIDEO EDITING","SOCIAL CONTENT"],icon:Video},
 {number:"03",name:"Strategic Leadership\n& Event Management",summary:"Leading cross-functional teams, executing major university-wide events, and managing operational and financial workflows.",tags:["LEADERSHIP","EVENTS","OPERATIONS"],icon:Users}
];
const facts=[["BASED IN","Multan, Pakistan"],["EDUCATION","BBA Banking & Finance · BZU"],["CGPA","3.67 / 4.00"],["CURRENT ROLE","Content Creator & Vice President"],["LANGUAGES","Urdu (Native) · English (Professional) · Chinese & Arabic (Conversational)"],["PHONE","+92 331 974 3275"]];

function Reveal({children,className="",delay=0}:{children:ReactNode;className?:string;delay?:number}) {
 const reduced=useReducedMotion();
 return <motion.div className={className} initial={reduced?false:{opacity:0,y:26}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>;
}
function Marker({number,label,right}:{number:string;label:string;right?:string}){
 return <div className="flex items-center justify-between gap-3 border-t border-line py-6"><p className="eyebrow text-fog"><span className="mr-4 text-accent">/{number}</span>{label}</p>{right&&<span className="hidden text-[11px] tracking-widest text-fog sm:block">{right}</span>}</div>;
}
function Visual({category}:{category:Project["category"]}){
 if(category==="Writing") return <div className="decor-grid relative flex min-h-56 flex-col justify-between overflow-hidden rounded-xl border border-[#353b2a] bg-[#1b2515] p-7 md:min-h-64"><div className="eyebrow relative text-accent">SEARCH. WRITE. RANK.</div><div className="relative text-[clamp(58px,8vw,105px)] font-black leading-[.8] tracking-[-.09em]">WORDS<br/><span className="text-accent">WORK.</span></div><div className="relative flex justify-between border-t border-white/20 pt-4 text-[10px] tracking-widest text-white/50"><span>CONTENT WITH PURPOSE</span><span>01 / SEO</span></div></div>;
 if(category==="Creative") return <div className="decor-slash relative flex min-h-56 flex-col items-center justify-center overflow-hidden rounded-xl border border-[#4c2f3c] bg-[#271722] p-8 md:min-h-64"><div className="absolute -left-16 -top-24 h-80 w-80 rounded-full bg-rose-400/20 blur-3xl"/><div className="relative mb-5 flex h-24 w-24 items-center justify-center rounded-full border border-[#ffc7ce]/40 bg-[#ffc7ce]/10"><Video size={38} className="text-[#ffc7ce]"/></div><div className="relative text-center text-4xl font-black leading-[.95] tracking-[-.07em] text-[#ffd7de]">THE SCROLL<br/>STOPS HERE.</div><span className="absolute bottom-5 text-[10px] tracking-widest text-[#ffc7ce]/60">@HEHE_USSSS</span></div>;
 if(category==="Leadership") return <div className="decor-slash relative flex min-h-56 flex-col justify-end overflow-hidden rounded-xl border border-[#333e56] bg-[#192438] p-8 md:min-h-64"><span className="absolute -right-2 -top-16 text-[250px] font-black leading-none tracking-[-.13em] text-blue-200/[.09]">20</span><span className="eyebrow relative mb-5 text-[#aec7ff]">PEOPLE. PURPOSE. PROGRESS.</span><span className="relative text-6xl font-black leading-[.88] tracking-[-.08em]">LEAD<br/><span className="text-[#9bb5ff]">FORWARD.</span></span><span className="absolute bottom-6 right-6 rounded-full border border-blue-300/40 px-3 py-1 text-xs text-blue-200">VP / IBF</span></div>;
 return <div className="decor-grid relative flex min-h-56 flex-col justify-between overflow-hidden rounded-xl border border-[#49402c] bg-[#292319] p-7 md:min-h-64"><div className="eyebrow text-[#e8cd86]">ANALYZE / RECONCILE</div><div className="flex h-24 items-end gap-2">{[30,48,39,76,57,88,69,100,78].map((h,i)=><div key={i} className="w-full rounded-t-sm bg-[#e8cd86]" style={{height:h+"%",opacity:.28+i*.07}}/>)}</div><div className="flex items-end justify-between border-t border-white/20 pt-4 text-4xl font-black leading-[.95] tracking-[-.07em] text-[#fff1c5]">DETAIL IS<br/>EVERYTHING.<ArrowUpRight className="text-[#e8cd86]"/></div></div>;
}
function ProjectCard({project}:{project:Project}){
 return <Reveal><article className="card h-full p-3 md:p-4"><Visual category={project.category}/><div className="px-3 pb-4 pt-7 md:px-4"><div className="flex justify-between gap-3"><span className="eyebrow text-accent">{project.eyebrow}</span><span className="text-xs text-fog">{project.number} / 04</span></div><h3 className="mt-5 whitespace-pre-line text-[clamp(30px,3.6vw,42px)] font-bold leading-[1.03] tracking-[-.06em]">{project.name}</h3><p className="mt-3 text-sm leading-relaxed text-fog">{project.role} · {project.period}</p><div className="my-6 border-y border-line py-5"><strong className="block text-6xl font-black leading-none tracking-[-.09em]">{project.metric}</strong><span className="eyebrow mt-3 block text-fog">{project.metricLabel}</span></div><ul className="space-y-3">{project.details.map(line=><li key={line} className="flex gap-3 text-[13px] leading-relaxed text-[#b3b3b3]"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent"/>{line}</li>)}</ul>{project.category==="Creative"&&<a href={INSTA} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-accent hover:underline">View @hehe_ussss <ArrowUpRight size={16}/></a>}</div></article></Reveal>;
}
function ContactForm(){
 const[name,setName]=useState("");const[email,setEmail]=useState("");const[type,setType]=useState("");const[message,setMessage]=useState("");const[opened,setOpened]=useState(false);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const subject="Portfolio enquiry: "+type+" — "+name;const body="Hi Famiya,\n\n"+message+"\n\nProject type: "+type+"\nName: "+name+"\nReply to: "+email;setOpened(true);window.location.href="mailto:"+EMAIL+"?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(body);}
 return <form onSubmit={submit} className="space-y-5" aria-label="Project enquiry form"><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="contactName" className="eyebrow mb-2 block text-[#bcbcbc]">YOUR NAME *</label><input id="contactName" className="input" placeholder="How should I call you?" autoComplete="name" maxLength={100} required value={name} onChange={e=>setName(e.target.value)}/></div><div><label htmlFor="contactEmail" className="eyebrow mb-2 block text-[#bcbcbc]">EMAIL ADDRESS *</label><input id="contactEmail" className="input" placeholder="you@company.com" type="email" autoComplete="email" maxLength={200} required value={email} onChange={e=>setEmail(e.target.value)}/></div></div><div><label htmlFor="contactType" className="eyebrow mb-2 block text-[#bcbcbc]">PROJECT TYPE *</label><div className="relative"><select id="contactType" className="input appearance-none" required value={type} onChange={e=>setType(e.target.value)}><option value="" disabled>Select what you have in mind</option>{["SEO Content & Writing","Video Editing & Reels","Content Strategy","Event & Leadership Collaboration","Something Else"].map(v=><option key={v}>{v}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-4 text-fog" size={20}/></div></div><div><label htmlFor="contactMessage" className="eyebrow mb-2 block text-[#bcbcbc]">TELL ME ABOUT IT *</label><textarea id="contactMessage" className="input min-h-40 resize-y" placeholder="The big idea, the tiny details, your wildest brief…" required minLength={10} maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)}/></div><button className="group flex w-full items-center justify-between rounded-xl bg-accent px-6 py-5 text-sm font-black uppercase tracking-wide text-black transition-colors hover:bg-white" type="submit">Start the conversation <Send className="transition-transform group-hover:translate-x-1" size={18}/></button>{opened&&<p role="status" className="text-sm text-accent">Your email app should open with a prepared message. Press Send there to deliver it.</p>}<p className="text-xs leading-relaxed text-fog">This form opens your email application. It does not send or store your message on this site.</p></form>;
}
export default function Home(){
 const[menuOpen,setMenuOpen]=useState(false);const[filter,setFilter]=useState<Category>("All work");const[copied,setCopied]=useState(false);const{scrollYProgress}=useScroll();const scaleX=useSpring(scrollYProgress,{stiffness:100,damping:30,restDelta:.001});const filtered=filter==="All work"?projects:projects.filter(p=>p.category===filter);
 async function copy(){try{await navigator.clipboard.writeText(EMAIL);setCopied(true);}catch{const area=document.createElement("textarea");area.value=EMAIL;area.style.position="fixed";document.body.appendChild(area);area.select();setCopied(document.execCommand("copy"));area.remove();}}
 return <div className="min-h-screen overflow-x-hidden bg-ink"><motion.div className="fixed left-0 right-0 top-0 z-[100] h-[3px] origin-left bg-accent" style={{scaleX}}/>
 <header className="sticky top-0 z-50 border-b border-line bg-[#0a0a0a]/95 backdrop-blur-xl"><nav className="wrap flex h-[76px] items-center justify-between" aria-label="Primary navigation"><a href="#top" onClick={()=>setMenuOpen(false)} className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent text-xl font-black tracking-[-.08em] text-black">FZ</span><span className="hidden text-xs font-black uppercase tracking-wider sm:block">Famiya Zanaib<span className="mt-1 block text-[10px] font-normal text-fog">CREATIVE PORTFOLIO / 2026</span></span></a><div className="hidden items-center gap-9 md:flex">{[["Work","#work"],["About","#about"],["Expertise","#services"]].map(([t,h])=><a key={h} href={h} className="text-[13px] font-semibold text-fog transition-colors hover:text-white">{t}</a>)}</div><a href="#contact" className="hidden items-center gap-2 rounded-full border border-[#464646] px-5 py-3 text-xs font-bold hover:border-accent hover:text-accent md:inline-flex">Let&apos;s talk <ArrowUpRight size={15}/></a><button className="rounded-lg border border-line p-2 md:hidden" type="button" onClick={()=>setMenuOpen(!menuOpen)} aria-label={menuOpen?"Close navigation":"Open navigation"} aria-expanded={menuOpen} aria-controls="mobile-nav">{menuOpen?<X/>:<Menu/>}</button></nav><AnimatePresence>{menuOpen&&<motion.div id="mobile-nav" initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} exit={{opacity:0,height:0}} className="wrap overflow-hidden md:hidden">{[["Work","#work"],["About","#about"],["Expertise","#services"],["Contact","#contact"]].map(([t,h])=><a key={h} href={h} onClick={()=>setMenuOpen(false)} className="block border-t border-line py-4 text-sm font-semibold">{t}</a>)}</motion.div>}</AnimatePresence></header>
 <main id="top"><section className="relative overflow-hidden pb-20 pt-16 md:pb-28 md:pt-28"><div className="pointer-events-none absolute -right-56 -top-32 h-[700px] w-[700px] rounded-full bg-accent/10 blur-[150px]"/><div className="wrap relative"><Reveal className="mb-12 flex flex-wrap justify-between gap-4"><span className="eyebrow flex items-center gap-3 text-[#bcbcbc]"><span className="h-2 w-2 rounded-full bg-accent"/>THE WORK OF A CURIOUS MIND</span><span className="eyebrow text-[#777]">MULTAN, PAKISTAN · AVAILABLE WORLDWIDE</span></Reveal><motion.h1 initial={{opacity:0,y:36}} animate={{opacity:1,y:0}} transition={{duration:.9,ease:[.22,1,.36,1]}} className="hero-font text-[clamp(76px,15vw,224px)]"><span className="block">FAMIYA</span><span className="mt-3 block">ZANAIB<span className="text-accent">.</span></span></motion.h1><div className="mt-12 grid items-end gap-8 border-t border-line pt-9 md:grid-cols-2 md:gap-20"><Reveal><p className="eyebrow mb-4 text-accent">CONTENT WRITER · SEO STRATEGIST · EDITOR</p><p className="max-w-lg text-base leading-[1.85] text-[#bcbcbc]">Results-driven Content Writer, SEO Strategist and Short-form Video Editor with <strong className="text-white">3+ years of experience</strong> delivering <strong className="text-white">1,000+ high-quality articles</strong> and engaging digital content.</p></Reveal><Reveal delay={.1}><div className="md:ml-auto"><p className="mb-6 max-w-sm text-xl font-bold leading-snug tracking-tight">BBA Banking & Finance scholar (3.67 CGPA). First female VP of IBF Society. Digital creator.</p><div className="flex flex-wrap gap-3"><a href="#work" className="inline-flex items-center gap-3 rounded-full bg-white px-6 py-4 text-xs font-black uppercase tracking-wider text-black transition-colors hover:bg-accent">Explore work <ArrowDownRight size={17}/></a><a href="#contact" className="inline-flex items-center gap-3 rounded-full border border-[#515151] px-6 py-4 text-xs font-black uppercase tracking-wider hover:border-white">Get in touch <ArrowUpRight size={17}/></a></div></div></Reveal></div><Reveal className="mt-20 grid grid-cols-2 gap-3 md:grid-cols-4">{[["1,000+","ARTICLES DELIVERED"],["3+","YEARS OF EXPERIENCE"],["3.67","BBA CGPA"],["20+","TEAM MEMBERS LED"]].map(([v,k])=><div key={k} className="rounded-2xl border border-line bg-panel px-5 py-7 md:px-7 md:py-9"><p className="text-[clamp(40px,5vw,68px)] font-black leading-none tracking-[-.09em]">{v}</p><p className="eyebrow mt-5 text-fog">{k}</p></div>)}</Reveal><div className="mt-10 flex items-center gap-2 text-xs text-[#888]"><ArrowDownRight size={18}/> SCROLL TO EXPLORE <span className="ml-auto text-accent">01 — 05</span></div></div></section>
 <div className="marquee border-y border-line bg-[#111] py-4" aria-hidden="true"><div className="marquee-track">{Array.from({length:4}).flatMap((_,i)=>["WORDS THAT WORK","✳","STORIES THAT STAY","✳","IDEAS INTO IMPACT","✳"].map((v,j)=><span key={i+"-"+j} className={"text-xs font-black tracking-widest "+(v==="✳"?"text-accent":"text-fog")}>{v}</span>))}</div></div>
 <section id="services" className="wrap pb-24 pt-24 md:pb-32 md:pt-32"><Marker number="01" label="WHAT I DO" right="THREE CORE PILLARS"/><Reveal className="mb-12 mt-9 flex flex-wrap items-end justify-between gap-6"><h2 className="section-font text-[clamp(52px,8vw,110px)]">SKILLS THAT<br/><span className="text-accent">DELIVER.</span></h2><p className="max-w-sm text-sm leading-[1.8] text-fog">From the right words to powerful visuals and strong teams. Strategy and execution, in one place.</p></Reveal><div className="grid gap-4 md:grid-cols-3">{services.map(s=><Reveal key={s.number}><article className="card flex h-full flex-col p-7 md:p-8"><div className="mb-14 flex items-center justify-between"><span className="eyebrow text-accent">/{s.number}</span><s.icon size={25} className="text-accent"/></div><h3 className="whitespace-pre-line text-3xl font-bold leading-tight tracking-[-.05em]">{s.name}</h3><p className="mt-6 flex-1 text-sm leading-[1.85] text-[#b6b6b6]">{s.summary}</p><div className="mt-9 flex flex-wrap gap-2">{s.tags.map(t=><span key={t} className="rounded-full border border-[#404040] px-3 py-2 text-[9px] font-bold tracking-wider text-[#a9a9a9]">{t}</span>)}</div></article></Reveal>)}</div></section>
 <section id="work" className="border-y border-line bg-[#0e0e0e] py-24 md:py-32"><div className="wrap"><Marker number="02" label="SELECTED WORK" right="2024 — PRESENT"/><Reveal className="mt-10 flex flex-wrap items-end justify-between gap-7"><h2 className="section-font text-[clamp(52px,8vw,110px)]">PROOF IN<br/><span className="text-accent">THE WORK.</span></h2><p className="max-w-xs text-sm leading-[1.85] text-fog">Each project and role has a story. These are the chapters that define the work.</p></Reveal><div className="mb-8 mt-12 flex flex-wrap gap-2" aria-label="Filter work">{categories.map(c=><button type="button" key={c} onClick={()=>setFilter(c)} aria-pressed={filter===c} className={"rounded-full border px-5 py-3 text-xs font-bold transition-colors "+(filter===c?"border-accent bg-accent text-black":"border-[#393939] text-fog hover:border-white hover:text-white")}>{c}</button>)}</div><motion.div layout className="grid items-stretch gap-5 md:grid-cols-2">{filtered.map(p=><ProjectCard key={p.number} project={p}/>)}</motion.div></div></section>
 <section id="about" className="wrap py-24 md:py-32"><Marker number="03" label="THE PERSON" right="A LITTLE MORE ABOUT ME"/><div className="mt-12 grid gap-14 md:grid-cols-[1fr_1fr] md:gap-20"><Reveal><h2 className="section-font text-[clamp(52px,6.5vw,96px)]">MORE THAN<br/><span className="text-accent">A BYLINE.</span></h2><p className="mt-9 max-w-lg text-base leading-[1.9] text-[#b4b4b4]">I&apos;m Famiya, a Multan-based writer and creator fascinated by what makes people pay attention. I combine meaningful words, engaging edits and a grounded understanding of business.</p><p className="mt-5 max-w-lg text-base leading-[1.9] text-[#b4b4b4]">As the first female Vice President of the IBF Society at Bahauddin Zakariya University, I&apos;ve learned that compelling communication and practical leadership go hand in hand.</p><div className="mt-9 flex flex-wrap gap-3"><span className="rounded-full border border-line px-4 py-3 text-xs text-fog">BBA Banking & Finance</span><span className="rounded-full border border-line px-4 py-3 text-xs text-fog">Creator · @hehe_ussss</span></div></Reveal><Reveal delay={.13}><div className="rounded-2xl border border-line bg-panel p-6 md:p-8"><div className="mb-6 flex items-center justify-between"><h3 className="text-xl font-bold">The fast facts.</h3><span className="eyebrow text-accent">AT A GLANCE</span></div>{facts.map(([label,value])=><div key={label} className="grid gap-2 border-t border-line py-5 sm:grid-cols-[130px_1fr] sm:gap-5"><span className="eyebrow text-fog">{label}</span><span className="text-sm font-semibold leading-relaxed text-white">{value}</span></div>)}<div className="border-t border-line pt-6"><a href={INSTA} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-accent hover:underline">@hehe_ussss <ArrowUpRight size={16}/></a></div></div></Reveal></div></section>
 <section id="contact" className="border-t border-line bg-[#0f0f0f] py-24 md:py-32"><div className="wrap"><Marker number="04" label="GET IN TOUCH" right="YOUR NEXT GREAT IDEA STARTS HERE"/><div className="mt-12 grid gap-14 md:grid-cols-2 md:gap-20"><Reveal><p className="eyebrow mb-6 text-accent">HAVE A CONCEPT IN MIND?</p><h2 className="section-font text-[clamp(48px,6vw,88px)]">Give me any<br/>concept, and<br/>I&apos;ll turn it into<br/><span className="text-accent">content that<br/>converts.</span></h2><p className="mt-8 max-w-md text-[15px] leading-[1.9] text-fog">A half-formed idea or an ambitious launch — tell me what you&apos;re imagining. We&apos;ll start there.</p><div className="mt-9 flex flex-wrap items-center gap-3"><button type="button" onClick={copy} className="inline-flex items-center gap-2 rounded-full border border-[#4b4b4b] px-5 py-4 text-xs font-bold hover:border-accent hover:text-accent">{copied?<Check size={17}/>:<Copy size={17}/>} {copied?"Email copied!":"Copy email"}</button><a href={"mailto:"+EMAIL} className="inline-flex items-center gap-2 text-sm text-fog hover:text-white">{EMAIL} <ArrowUpRight size={15}/></a></div><div className="mt-12 flex gap-3">{[[INSTA,Instagram,"Instagram"],[WHATSAPP,Phone,"WhatsApp"],["mailto:"+EMAIL,Mail,"Email"]].map(([url,Icon,label])=>{const TargetIcon=Icon as typeof Instagram;return <a key={label as string} href={url as string} aria-label={label as string} target={label==="Email"?undefined:"_blank"} rel="noreferrer" className="flex h-12 w-12 items-center justify-center rounded-full border border-line text-fog hover:border-accent hover:text-accent"><TargetIcon size={19}/></a>;})}</div></Reveal><Reveal delay={.12}><div className="rounded-2xl border border-line bg-panel p-6 md:p-9"><div className="mb-8 flex items-center justify-between border-b border-line pb-6"><div><p className="eyebrow text-accent">PROJECT INQUIRY</p><h3 className="mt-3 text-2xl font-bold tracking-tight">Tell me your idea.</h3></div><ArrowUpRight size={28}/></div><ContactForm/></div></Reveal></div></div></section></main>
 <footer className="border-t border-line bg-[#101010]"><div className="wrap pt-12"><div className="flex flex-wrap items-end justify-between gap-6 border-b border-line pb-12"><div><a href="#top" className="text-[clamp(43px,8vw,105px)] font-black leading-none tracking-[-.08em]">FAMIYA ZANAIB<span className="text-accent">.</span></a><p className="mt-4 text-xs tracking-wider text-fog">WORDS THAT WORK. STORIES THAT STAY.</p></div><a href="#top" className="rounded-full border border-line px-5 py-3 text-xs font-bold hover:border-accent">Back to top ↑</a></div><div className="flex flex-col justify-between gap-5 py-8 text-xs text-fog md:flex-row"><span>© {new Date().getFullYear()} Famiya Zanaib.</span><div className="flex flex-wrap gap-6"><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a><a href={INSTA} target="_blank" rel="noreferrer">Instagram ↗</a><a href={WHATSAPP} target="_blank" rel="noreferrer">WhatsApp ↗</a></div><span>MULTAN, PK · WORLDWIDE ONLINE</span></div></div></footer></div>;
}
